% MATLAB FILE TO PROCESS NS3 OUTPUT FILES,
% FOR CHAPTER 1 AND 2 OF THE REPORT,
% THAT WERE GENERATED BY THE ASSIGNMENT 
% SCRIPT, AS WRITTEN BY J.L.F. BETTING FOR
% THE WIRELESS NETWORKING COURSE AT TU DELFT

% VARIABLES
filename = 'chapter3OutFile.out'
step = 4;
width = 100;

% Rest of the programme
delimiter = ' ';
A = importdata(filename,delimiter,0);
A = A/1000; % conversion from kbit/s to Mbit/s
xAxis = -width:step:width;
figure(1)
plot(xAxis,A);
hold on;
grid on;
grid minor;
title('UDP throughput for situation 2, transmitter power = 110 dBm')
xlabel('Distance from the transmitter [m]');
ylabel('Throughput [Mbit/s]');



